<a href="https://colab.research.google.com/github/tanmayrathi/ML-PRACTICAL/blob/main/ML_7(CS23062).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tanmay Rathi (CS23062)

Aim: To apply support vector machine for classification and analyze the impact of different kernels on model accuracy.

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path="/content/drive/MyDrive/ML_Data/pulsar_stars - pulsar_stars.csv"
df=pd.read_csv(path)
df.head(5)

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0

In [ ]:
df.shape

(17898, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17898 entries, 0 to 17897
Data columns (total 9 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Mean of the integrated profile                17898 non-null  float64
 1   Standard deviation of the integrated profile  17898 non-null  float64
 2   Excess kurtosis of the integrated profile     17898 non-null  float64
 3   Skewness of the integrated profile            17898 non-null  float64
 4   Mean of the DM-SNR curve                      17898 non-null  float64
 5   Standard deviation of the DM-SNR curve        17898 non-null  float64
 6   Excess kurtosis of the DM-SNR curve           17898 non-null  float64
 7   Skewness of the DM-SNR curve                  17898 non-null  float64
 8   target_class                                  17898 non-null  int64
dtypes: float64(8), int64(1)
memory usage: 1.2 MB

In [ ]:
df.describe()

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
count,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000
mean,111.079968,46.549532,0.477857,1.770279,12.614400,26.326515,8.303556,104.857709,0.091574
std,25.652935,6.843189,1.064040,6.167913,29.472897,19.470572,4.506092,106.514540,0.288432
min,5.812500,24.772042,-1.876011,-1.791886,0.213211,7.370432,-3.139270,-1.976976,0.000000
25%,100.929688,42.376018,0.027098,-0.188572,1.923077,14.437332,5.781506,34.960504,0.000000
50%,115.078125,46.947479,0.223240,0.198710,2.801839,18.461316,8.433515,83.064556,0.000000
75%,127.085938,51.023202,0.473325,0.927783,5.464256,28.428104,10.702959,139.309330,0.000000
max,192.617188,98.778911,8.069522,68.101622,223.392141,110.642211,34.539844,1191.000837,1.000000

In [ ]:
df.columns

Index(['Mean of the integrated profile',
       'Standard deviation of the integrated profile',
       'Excess kurtosis of the integrated profile',
       'Skewness of the integrated profile', 'Mean of the DM-SNR curve',
       'Standard deviation of the DM-SNR curve',
       'Excess kurtosis of the DM-SNR curve', 'Skewness of the DM-SNR curve',
       'target_class'],
      dtype='object')

In [ ]:
df.isnull().any().any()

np.False_

In [ ]:
df.isnull().sum()

Mean of the integrated profile                  0
Standard deviation of the integrated profile    0
Excess kurtosis of the integrated profile       0
Skewness of the integrated profile              0
Mean of the DM-SNR curve                        0
Standard deviation of the DM-SNR curve          0
Excess kurtosis of the DM-SNR curve             0
Skewness of the DM-SNR curve                    0
target_class                                    0
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Mean of the integrated profile, Standard deviation of the integrated profile, Excess kurtosis of the integrated profile, Skewness of the integrated profile, Mean of the DM-SNR curve, Standard deviation of the DM-SNR curve, Excess kurtosis of the DM-SNR curve, Skewness of the DM-SNR curve, target_class]
Index: []

In [ ]:
df = df.rename(columns={'Mean of the integrated profile': 'IP Mean', 'Standard deviation of the integrated profile': 'IP Standard Deviation','Excess kurtosis of the integrated profile':'IP Kurtosis','Skewness of the integrated profile':'IP Skewness','Mean of the DM-SNR curve':'DM-SNR Mean','Standard deviation of the DM-SNR curve':'DM-SNR SD','Excess kurtosis of the DM-SNR curve':'DM-SNR Kurtosis','Skewness of the DM-SNR curve':'DM-SNR Skewness','target_class':'target'})

In [ ]:
X = df.drop(columns=['target'])
y = df['target']

In [ ]:
X.head()

,IP Mean,IP Standard Deviation,IP Kurtosis,IP Skewness,DM-SNR Mean,DM-SNR SD,DM-SNR Kurtosis,DM-SNR Skewness
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306

In [ ]:
X = pd.get_dummies(X, dtype=int)

In [ ]:
X.shape

(17898, 8)

In [ ]:
X.head(5)

,IP Mean,IP Standard Deviation,IP Kurtosis,IP Skewness,DM-SNR Mean,DM-SNR SD,DM-SNR Kurtosis,DM-SNR Skewness
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306

In [ ]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [ ]:
X.columns

Index(['IP Mean', 'IP Standard Deviation', 'IP Kurtosis', 'IP Skewness',
       'DM-SNR Mean', 'DM-SNR SD', 'DM-SNR Kurtosis', 'DM-SNR Skewness'],
      dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y,train_size=0.7,random_state=42)

In [ ]:
X_train.shape,X_test.shape

((12528, 8), (5370, 8))

In [ ]:
X_train.head()

,IP Mean,IP Standard Deviation,IP Kurtosis,IP Skewness,DM-SNR Mean,DM-SNR SD,DM-SNR Kurtosis,DM-SNR Skewness
12223,121.156250,48.372971,0.375485,-0.013165,3.168896,18.399367,7.449874,65.159298
1919,76.968750,36.175557,0.712898,3.388719,2.399666,17.570997,9.414652,102.722975
2753,130.585938,53.229534,0.133408,-0.297242,2.743311,22.362553,8.508364,74.031324
17220,156.398438,48.865942,-0.215989,-0.171294,17.471572,54.469915,2.958066,7.197842
12110,84.804688,36.117659,0.825013,3.274125,2.790134,20.618009,8.405008,76.291128

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler  = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[ 0.39398903,  0.27225212, -0.09759786, ..., -0.40338108,
        -0.19481754, -0.37780071],
       [-1.32725743, -1.52127273,  0.21878252, ..., -0.44578706,
         0.23837256, -0.02857034],
       [ 0.76130595,  0.98636783, -0.3245843 , ..., -0.2004973 ,
         0.038556  , -0.29531727],
       ...,
       [ 0.19435365, -0.48635278,  0.17242235, ..., -0.75001383,
         1.92294752,  1.91898259],
       [ 0.95911539,  0.50175114, -0.53401036, ..., -0.24457614,
        -0.20616758, -0.4040674 ],
       [ 0.37725131,  0.58093396, -0.12507761, ..., -0.74159513,
         2.05677923,  2.08022728]])

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svc=SVC()
svc.fit(X_train,y_train)
print('Accuracy Score')
print(accuracy_score(y_pred,y_test))

Accuracy Score
0.9789571694599628

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
cm=confusion_matrix(y_pred,y_test)
print(confusion_matrix(y_pred,y_test))

[[4863   92]
 [  21  394]]

In [ ]:
svc=SVC(C=100.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)

In [ ]:
accuracy_score(y_test,y_pred)

0.9802607076350093

In [ ]:
svc=SVC(C=1000.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
accuracy_score(y_test,y_pred)

0.9797020484171323

In [ ]:
liner_svc=SVC(kernel='linear',C=1.0)
liner_svc.fit(X_train,y_train)
y_pred=liner_svc.predict(X_test)
accuracy_score(y_test,y_pred)

0.9787709497206704

In [ ]:
liner_svc=SVC(kernel='linear',C=1.0)
liner_svc.fit(X_train,y_train)
y_pred=liner_svc.predict(X_test)
accuracy_score(y_test,y_pred)

0.9787709497206704

In [ ]:
liner_svc=SVC(kernel='linear',C=1000.0)
liner_svc.fit(X_train,y_train)
y_pred=liner_svc.predict(X_test)
accuracy_score(y_test,y_pred)

0.978584729981378

In [ ]:
liner_svc=SVC(kernel='poly',C=1.0)
liner_svc.fit(X_train,y_train)
y_pred=liner_svc.predict(X_test)
accuracy_score(y_test,y_pred)

0.9769087523277468

In [ ]:
liner_svc=SVC(kernel='sigmoid',C=1.0)
liner_svc.fit(X_train,y_train)
y_pred=liner_svc.predict(X_test)
accuracy_score(y_test,y_pred)

0.8772811918063315

In [ ]:
liner_svc=SVC(kernel='sigmoid',C=100.0)
liner_svc.fit(X_train,y_train)
y_pred=liner_svc.predict(X_test)
accuracy_score(y_test,y_pred)

0.8772811918063315